# Generated by Django 6.0.3 on 2026-04-24 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_company_description_customuser_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Hired', 'Hired'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20),
        ),
    ]
