# Generated by Django 6.0.4 on 2026-05-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password reset'), ('email_verification', 'Email verification')], default='password_reset', max_length=32),
        ),
    ]
