from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    AdminApplicationListView,
    AdminApplicationStatusView,
    AdminRecruiterDetailView,
    AdminRecruiterListCreateView,
    AdminRecruiterListView,
    AdminStatsView,
    AdminUserDetailView,
    AdminUserListView,
    AdminJobDetailView,
    AdminJobListCreateView,
    ApplicationDetailView,
    ApplicationListCreateView,
    CountryListView,
    ForgotPasswordView,
    JobDetailView,
    JobListCreateView,
    MessageInboxView,
    MessageSendView,
    MessageThreadView,
    NotificationListView,
    NotificationMarkReadView,
    ProfileView,
    RecruiterApplicationListView,
    RecruiterJobListView,
    ResetPasswordView,
    UserLoginView,
    UserProfileView,
    UserRegisterView,
)

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='user'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/extended/', UserProfileView.as_view(), name='profile-extended'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('jobs/', JobListCreateView.as_view(), name='job-list-create'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('applications/', ApplicationListCreateView.as_view(), name='application-list-create'),
    path('applications/<int:pk>/', ApplicationDetailView.as_view(), name='application-detail'),
    path('recruiter/applications/', RecruiterApplicationListView.as_view(), name='recruiter-applications'),
    path('recruiter/jobs/', RecruiterJobListView.as_view(), name='recruiter-jobs'),
    path('admin/applications/', AdminApplicationListView.as_view(), name='admin-application-list'),
    path('admin/applications/<int:pk>/status/', AdminApplicationStatusView.as_view(), name='admin-application-status'),
    path('admin/jobs/', AdminJobListCreateView.as_view(), name='admin-job-list-create'),
    path('admin/jobs/<int:pk>/', AdminJobDetailView.as_view(), name='admin-job-detail'),
    path('admin/users/', AdminUserListView.as_view(), name='admin-user-list'),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/recruiters/', AdminRecruiterListCreateView.as_view(), name='admin-recruiter-list'),
    path('admin/recruiters/<int:pk>/', AdminRecruiterDetailView.as_view(), name='admin-recruiter-detail'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/mark-read/', NotificationMarkReadView.as_view(), name='notifications-mark-read'),
    path('messages/', MessageInboxView.as_view(), name='message-inbox'),
    path('messages/send/', MessageSendView.as_view(), name='message-send'),
    path('messages/thread/<int:user_id>/', MessageThreadView.as_view(), name='message-thread'),
    path('messages/contacts/', AdminRecruiterListView.as_view(), name='message-contacts'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
]
